user  nobody;
worker_processes  4;

error_log /data/user/0/ru.kslabs.ksweb/components/log/nginx/nginx.log;
pid /data/user/0/ru.kslabs.ksweb/components/log/nginx/nginx.pid;

#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/error.log;


events {
    worker_connections  1024;
}


http {

	large_client_header_buffers 4 16k;

access_log /data/user/0/ru.kslabs.ksweb/components/log/nginx/access.log;

    include       /data/data/ru.kslabs.ksweb/components/nginx/conf/mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    gzip  on;

    # 全局开启目录浏览
    autoindex on;
    autoindex_exact_size off;
    autoindex_localtime on;

	#client_max_body_size 20M;
	
#begin_hosts (do not remove this label!)
include /data/user/0/ru.kslabs.ksweb/components/nginx/conf/localhost_host.conf;
include /data/user/0/ru.kslabs.ksweb/components/nginx/conf/localhost_b96c609e-fd81-4134-8e7b-c8c4989085da_host.conf;
include /data/user/0/ru.kslabs.ksweb/components/nginx/conf/localhost_a024f876-e4e2-42c2-b4c8-69ee2bd49dbf_host.conf;
#end_hosts (do not remove this label!)

    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443;
    #    server_name  localhost;

    #    ssl                  on;
    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_timeout  5m;

    #    ssl_protocols  SSLv2 SSLv3 TLSv1;
    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers   on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}







最后操作
 
1. 保存配置文件
​
2. KSWEB 关闭 Nginx 再重新打开
​
3. 清空目录内所有  index  索引文件，访问目录，即可正常展示文件列表。


index 索引文件包含  index.php  index.html
