kswrn里  修改完nginx.conf

lighttpd就不能用了
一样用哪个都可以



ksweb里修改了nginx.conf

全局目录浏览

lighttpd/conf
受到影响  会出现403



云服务器里安装nginx   好用不报错


不要安装lighttpd    容易出问题

ksweb里用lighttpd  好用

不要修改nginx.conf
为全局目录浏览

lighttpd/conf
柜受到影响  会出现403


轻应用服务器，用ai助手协助完成

提示词如下

配置Nginx，默认首页优先级 index.php、index.html、index.htm，开启目录浏览，

写入默认首页，生成站点配置并重载Nginx；同时安装php-fpm，

设置开机自启并启动服务，保证PHP正常解析





轻应用服务器里lighttpd不好配置

php-fpm，容易出错

不要同时安装nginx和lighttpd  以及apache

建议只安装nginx


安装的太多方行端口容易冲突以及php-fpm解析会出问题


建议只安卓nginx

开启全局目录浏览功能配置简单







